// <auto-generated />
using System;
using LojaRoupasApi.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaRoupasApi.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    partial class ConnectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.Carrinho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Carrinhos", (string)null);
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdCarrinho")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdCarrinho")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Compra", (string)null);
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.ItemCarrinho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdCarrinho")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCarrinho");

                    b.HasIndex("IdProduto");

                    b.ToTable("ItemCarrinho", (string)null);
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.ProdutoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto")
                        .IsUnique();

                    b.ToTable("ProdutoEstoque", (string)null);
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Datanascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.Carrinho", b =>
                {
                    b.HasOne("LojaRoupasApi.Domain.Models.Usuario", "Usuario")
                        .WithOne("Carrinho")
                        .HasForeignKey("LojaRoupasApi.Domain.Models.Carrinho", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.Compra", b =>
                {
                    b.HasOne("LojaRoupasApi.Domain.Models.Carrinho", "Carrinho")
                        .WithOne("Compra")
                        .HasForeignKey("LojaRoupasApi.Domain.Models.Compra", "IdCarrinho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojaRoupasApi.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.ItemCarrinho", b =>
                {
                    b.HasOne("LojaRoupasApi.Domain.Models.Carrinho", "Carrinho")
                        .WithMany("Items")
                        .HasForeignKey("IdCarrinho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojaRoupasApi.Domain.Models.Produto", "Produto")
                        .WithMany("ItemCarrinhos")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.ProdutoEstoque", b =>
                {
                    b.HasOne("LojaRoupasApi.Domain.Models.Produto", "Produto")
                        .WithOne("ProdutoEstoque")
                        .HasForeignKey("LojaRoupasApi.Domain.Models.ProdutoEstoque", "IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.Carrinho", b =>
                {
                    b.Navigation("Compra")
                        .IsRequired();

                    b.Navigation("Items");
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.Produto", b =>
                {
                    b.Navigation("ItemCarrinhos");

                    b.Navigation("ProdutoEstoque")
                        .IsRequired();
                });

            modelBuilder.Entity("LojaRoupasApi.Domain.Models.Usuario", b =>
                {
                    b.Navigation("Carrinho")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
